package diff

import (
	"fmt"
	"strings"
)

// RenderPRBody generates a markdown PR body from a changeset.
func RenderPRBody(cs *ChangeSet) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("## Model Catalog Update: %s\n\n", cs.Provider))
	b.WriteString(fmt.Sprintf("**Summary**: %d new, %d updated, %d unchanged, %d deprecation candidates\n\n",
		len(cs.New), len(cs.Updated), cs.Unchanged, len(cs.DeprecationCandidates)))

	// New models table
	if len(cs.New) > 0 {
		b.WriteString("### New Models\n\n")
		b.WriteString("| Model | Family | Status | Context Window |\n")
		b.WriteString("|-------|--------|--------|----------------|\n")
		for _, m := range cs.New {
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %d |\n",
				m.Name, m.Model.Family, m.Model.Status, m.Model.Limits.MaxTokens))
		}
		b.WriteString("\n")
	}

	// Updated models table
	if len(cs.Updated) > 0 {
		b.WriteString("### Updated Models\n\n")
		b.WriteString("| Model | Changed Fields | Details |\n")
		b.WriteString("|-------|---------------|----------|\n")
		for _, u := range cs.Updated {
			fields := make([]string, 0, len(u.Changes))
			details := make([]string, 0, len(u.Changes))
			for _, c := range u.Changes {
				fields = append(fields, c.Field)
				details = append(details, fmt.Sprintf("%s: %v → %v", c.Field, c.OldValue, c.NewValue))
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",
				u.Name, strings.Join(fields, ", "), strings.Join(details, "; ")))
		}
		b.WriteString("\n")
	}

	// Deprecation candidates
	if len(cs.DeprecationCandidates) > 0 {
		b.WriteString("### Deprecation Candidates\n\n")
		b.WriteString("These models exist in the catalog but were not found by the provider API. ")
		b.WriteString("They may have been renamed, deprecated, or temporarily unavailable.\n\n")
		for _, m := range cs.DeprecationCandidates {
			b.WriteString(fmt.Sprintf("- `%s` (%s)\n", m.Name, m.Model.Family))
		}
		b.WriteString("\n")
	}

	// Possible renames
	if len(cs.PossibleRenames) > 0 {
		b.WriteString("### Possible Renames\n\n")
		b.WriteString("| Old Name | New Name | Reason |\n")
		b.WriteString("|----------|----------|--------|\n")
		for _, r := range cs.PossibleRenames {
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", r.OldName, r.NewName, r.Reason))
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString("*Generated by sentinel*\n")

	return b.String()
}

// RenderDiffSummary generates a human-readable diff summary for CLI output.
func RenderDiffSummary(cs *ChangeSet) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("Provider: %s\n", cs.Provider))
	b.WriteString(fmt.Sprintf("  New:         %d\n", len(cs.New)))
	b.WriteString(fmt.Sprintf("  Updated:     %d\n", len(cs.Updated)))
	b.WriteString(fmt.Sprintf("  Unchanged:   %d\n", cs.Unchanged))
	b.WriteString(fmt.Sprintf("  Deprecation: %d\n", len(cs.DeprecationCandidates)))
	b.WriteString(fmt.Sprintf("  Renames:     %d\n", len(cs.PossibleRenames)))

	if len(cs.New) > 0 {
		b.WriteString("\n  New models:\n")
		for _, m := range cs.New {
			b.WriteString(fmt.Sprintf("    + %s\n", m.Name))
		}
	}

	if len(cs.Updated) > 0 {
		b.WriteString("\n  Updated models:\n")
		for _, u := range cs.Updated {
			fields := make([]string, 0, len(u.Changes))
			for _, c := range u.Changes {
				fields = append(fields, c.Field)
			}
			b.WriteString(fmt.Sprintf("    ~ %s [%s]\n", u.Name, strings.Join(fields, ", ")))
		}
	}

	if len(cs.DeprecationCandidates) > 0 {
		b.WriteString("\n  Deprecation candidates:\n")
		for _, m := range cs.DeprecationCandidates {
			b.WriteString(fmt.Sprintf("    - %s\n", m.Name))
		}
	}

	return b.String()
}
